name: dbt CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery

      - name: Setup Google credentials
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
        run: |
          echo "$GCP_KEY" > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json

      - name: dbt debug
        run: dbt debug --profiles-dir .

      - name: dbt run
        run: dbt run --profiles-dir .

      - name: dbt test
        run: dbt test --profiles-dir .