name: dbt CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Write GCP key
        run: echo '${{ secrets.GCP_KEY }}' > key.json

      - name: Check key file
        run:
          cat key.json

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          dbt_demo_project:
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: ${{ secrets.GCP_PROJECT }}
                dataset: ducks_dataset
                keyfile: key.json
                location: europe-west2
                threads: 4
            target: dev
          EOF

      - name: Run dbt
        working-directory: dbt_demo_project
        run: |
               dbt debug
               dbt run
               dbt test